### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by SandPoot** [tgstation/tgstation-server#1012]
Note that this repository does not contain any client code (With the exception of the web control panel which can be found in [its own repository](https://github.com/tgstation/tgstation-server-control-panel)). Any client issues should be reported to their respective codebases.

Please include:

- A description of the issue.
Errors while compiling
- The version of tgstation-server you were using.
4.2.4
- Reproduction steps for the issue if possible (Very helpful).
Trying to compile through any means
- Relevent server logs, request logs, and screenshots if possible.
https://pastebin.com/ZqnGa2Yr

**Comment by Cyberboss** [comment]
This looks like an issue when posting GitHub comments. Do you have that feature enabled? As a workaround you can disable it.

**Comment by SandPoot** [comment]
I'll give it a look.

**Comment by SandPoot** [comment]
Yea, tested it, it was the comments.
