### ISSUE TITLE
Monitor crashing? bot requested to report it

### ISSUE THREAD

**Issue by SandPoot** [tgstation/tgstation-server#1014]
Note that this repository does not contain any client code (With the exception of the web control panel which can be found in [its own repository](https://github.com/tgstation/tgstation-server-control-panel)). Any client issues should be reported to their respective codebases.

Please include:

- A description of the issue.
Activated experimental watch dog, getting spam from it (need some help about getting such logs, it's on the default loc)
- The version of tgstation-server you were using.
4.2.4
- Reproduction steps for the issue if possible (Very helpful).
Enable experimental watchdog, host
- Relevent server logs, request logs, and screenshots if possible.
(need help getting it)

**Comment by Cyberboss** [comment]
By default TGS stores logs in the following locations:

Windows: C:/ProgramData/tgstation-server/logs
Linux: /usr/share/tgstation-server/logs
Docker: /tgs_logs (whatever that's mapped to)

I'll need to see them to figure out how this happened

**Comment by Cyberboss** [comment]
Wait, you're saying this is the experimental watchdog? Note that one is currently not supported at all. I don't even know if it still works even slightly.

**Comment by SandPoot** [comment]
Yes, thought it was fixed after that changelog talking about not spamming when closed.

**Comment by Cyberboss** [comment]
There are [several known issues with it currently](https://github.com/tgstation/tgstation-server/labels/Watchdog%3A%20Experimental). I recommend the Windows Watchdog on windows and the Basic watchdog on Linux
![image](https://user-images.githubusercontent.com/8171642/82693949-6ed46d00-9c30-11ea-85ac-0fdcd5e68dbc.png)

**Comment by SandPoot** [comment]
Right, thanks.
