### ISSUE TITLE
API spec circular reference

### ISSUE THREAD

**Issue by alexkar598** [tgstation/tgstation-server#1023]
Api version 6.4.0

 - User --> CreatedBy --> User
Fixed by making the CreatedBy field a ShallowUser that doesnt contain such a field OR
making the CreatedBy field an id to the User

 - CompileJob --> RevisionInformation --> compileJobs[] --> CompileJob
Fixed by removing the compileJobs property OR
making it an id to the CompileJob

**Comment by Cyberboss** [comment]
Major API change

**Comment by Cyberboss** [comment]
Actually no, this is minor
