### ISSUE TITLE
Server stops relaying to irc or discord randomly

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation-server#104]
The bot may disconnect from irc or just start ignoring discord, you have to disable and re-enable the chat interface to fix it.

**Comment by MrStonedOne** [comment]
https://github.com/tgstation/byond-server

**Comment by LetterJay** [comment]
I've tried disabling chat, applying, then enabling chat, applying in regards to discord yet the only messages it seems to relay are from Watchdog. And yes, I have posted the channel ID in the correct boxes.

**Comment by Cyberboss** [comment]
Hopefully #126 kills this

**Comment by JamieH** [comment]
It looks like the config is being randomly wiped at times too.
