### ISSUE TITLE
event script arguments not wrapped for paths with spaces

### ISSUE THREAD

**Issue by silicons** [tgstation/tgstation-server#1112]
![image](https://user-images.githubusercontent.com/2003111/91685216-93cd5b80-eb0e-11ea-8e8b-3b366ac99691.png)
![image](https://user-images.githubusercontent.com/2003111/91685222-962fb580-eb0e-11ea-80bf-124022b05af8.png)
![image](https://user-images.githubusercontent.com/2003111/91685225-97f97900-eb0e-11ea-89aa-c2bd1bacfd6a.png)
![image](https://user-images.githubusercontent.com/2003111/91685229-992aa600-eb0e-11ea-8bc2-9ec5a88c0bb4.png)

helpies

**Comment by Cyberboss** [comment]
Easy fix, just quote arguments (and escape inner quotes) before executing scripts in src/TGS.Host/Components/StaticFiles/Configuration.cs
