### ISSUE TITLE
Add a header to identity a response as coming from TGS

### ISSUE THREAD

**Issue by alexkar598** [tgstation/tgstation-server#1113]
**Is your feature request related to a problem? Please describe.**
Inability to determine if a response is originating from a proxy server or TGS itself

**Describe the solution you'd like**
Add a header to determine that a response has originated from TGS

**Describe alternatives you've considered**
adding a X-Powered-By header
adding a X-TG-Server header

**Additional context**
Only the Server: Kestrel header can be used to identify but it would get overwritten by proxy servers
![img](https://i.imgur.com/i7HKdpf.png)

**Comment by Cyberboss** [comment]
This could be handled with another request pipeline layer before the 500 error handler.

**Comment by Cyberboss** [comment]
Let's use `X-Powered-By`

**Comment by Cyberboss** [comment]
#1134
