### ISSUE TITLE
Access-Control-Max-Age header

### ISSUE THREAD

**Issue by alexkar598** [tgstation/tgstation-server#1150]
**Is your feature request related to a problem? Please describe.**
The browser has to spam OPTIONS requests to the server, i think its refusing to cache the CORS headers if its not explicitly toldto

**Describe the solution you'd like**
Id like for TGS to send the Access-Control-Max-Age header of like 86400 seconds(24 hours)

**Additional context**
[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Max-Age]()

I don't think those headers ever change so caching it should be fine?

**Comment by Cyberboss** [comment]
https://github.com/tgstation/tgstation-server/tree/PreflightStuff
