### ISSUE TITLE
I've seen the API return a negative progress value for a git job before

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation-server#1168]
wack

**Comment by Cyberboss** [comment]
I think this would be fixed in 4.15.1

**Comment by AffectedArc07** [comment]
Still happens
![image](https://user-images.githubusercontent.com/25063394/175022806-e9c50a31-60c7-45cc-b0ef-df0a5a409828.png)

**Comment by AffectedArc07** [comment]
![image](https://user-images.githubusercontent.com/25063394/177652125-adeae419-66af-4e78-a1b0-445724691b7b.png)
Another one

**Comment by Cyberboss** [comment]
Probably fixed with #1387
