### ISSUE TITLE
POST / User with a non existant group returns 410 which is undocumented

### ISSUE THREAD

**Issue by alexkar598** [tgstation/tgstation-server#1177]
**Describe the bug**
POST /User can return http 410 which is undocumented

**To Reproduce**
Request/Response
![](https://i.imgur.com/zf9mGlz.png)

**Expected behavior**
Expected a documented behaviour in the spec

**Logs**
```
[18:48:09] dbg: Tgstation.Server.Host.Controllers.UserController (Instance:|Job:|Request:POST /User|User:1|Monitor:|Bridge:|Chat:|IR:)
    Starting API request: Version: 8.0.0. User-Agent: Not-A-Furry/1.0.0.0
```

**Server State: (please complete the following information):**
 - OS: Win 10
 - Version: Commit 007c40fe0ff165b3047dbb7fb79c11dba6b18e25
 - Database Type/Version: 10.5.8-MariaDB
 - BYOND Version Used: N/A
 - git Repository Used: N/A
 - Origin Commit hash Used: N/A
 - Active Test Merges: N/A
 - Client Version: N/A

**Additional context**
nyaaaaaaaaa~

**Comment by Cyberboss** [comment]
> User-Agent: Not-A-Furry/1.0.0.0
