### ISSUE TITLE
Webpanel channel.json

### ISSUE THREAD

**Issue by alexkar598** [tgstation/tgstation-server#1205]
This feature is in two parts:

1) a new configuration value which can either be null, "local" or a string("local" is also a string but w/e, tldr either null or a string)
2) /app/channel.json needs to return the following json:
```json
{
    "formatVersion": 1,
    "channel": <string>
}
```

`channel` should be generated based on the config entry
1) ``"local"`` should set ``channel`` to ``"/"``
2) ``null`` should set channel to a new compile time property, this property would contain a default channel url which would be changed every once in a while whenever theres a breaking change in TGS that requires a new webpanel which wouldnt be backwards compatible
3) if its neither ``null`` or ``"local"``, then it should simply be the value of the new config option

**Comment by AffectedArc07** [comment]
Needs updating to be in YAML format.

**Comment by Cyberboss** [comment]
No, this is an API endpoint, which should remain JSON. The config would be in YAML though

**Comment by AffectedArc07** [comment]
Good point
