### ISSUE TITLE
Automaticly resolve DMI conflicts in TGS

### ISSUE THREAD

**Issue by BraveMole** [tgstation/tgstation-server#1236]
**Is your feature request related to a problem? Please describe.**

Two PRs with conflicts in a dmi file cannot be test merged at the same time, even if both are simply adding an icon.
We run into this problem on TGMC all the time

**Describe the solution you'd like**

If the conflict resolution is simple (aka the PRs are not modifying the same icon, just simple deletion and addition that are not conflicting), make it possible to TM them both at the same time

**Describe alternatives you've considered**

A tool to deal with DMI conflicts already exist and works pretty well, but that script (Resolve Icon Conflicts.bat , present on tg repo) . Adapating that script to run on TM would probably be a nice feature to have

**Comment by Cyberboss** [comment]
For reference, this would likely involve re-implementing the DMI merge driver in C# https://github.com/tgstation/tgstation/blob/master/tools/dmi/merge_driver.py

And it should be done in a modular way (`IMergeDriver`). I can imagine someone asking for a .dmm merge driver eventuallyy yoo.

**Comment by Cyberboss** [comment]
Would rather this be implemented in an event script that just installs the git hook
