### ISSUE TITLE
TGS4 Client/Server Feature: Client shows number of active players logged in

### ISSUE THREAD

**Issue by ORCACommander** [tgstation/tgstation-server#1248]
**Is your feature request related to a problem? Please describe.**

Right now I have a problem. Granted some if it is my own doing. the hardware i run my server on, its performance is easily disrupted by random log ins, and I never trust the game to go to sleep correctly if no one is actively logged in. Sometimes the actions you can perform in TGS 4 can be highly disruptive to any players currently logged in. logging into the server via byond just to do a player count check. Since my server is very low pop, average 10 high of 20 people sudden round restarts are highly disruptive. pushing new deployments can cut into available processor resources resulting in time dilation as well.

**Describe the solution you'd like**

On an instance's dream demon page, Can we have an Active Player count and also the ability to push a Sys Admin message to the server

**Describe alternatives you've considered**

A possible alternative would be the option to have tgs4 not run dream deamon in a headless state so we can use the existing byond made tools for this

**Additional context**

**Comment by Cyberboss** [comment]
Can this not be solved via a discord/IRC bot? Most all /tg/ derivatives have `/datum/tgs_chat_command/check` which will print the amount of online players with the `!tgs check` command.

I don't really want to make this available to the TGS clients if I can avoid it because piping data from DD -> TGS and then through the backend to the API is a complicated process. And even after all that, it wouldn't work if the codebase doesn't support the DMAPI.

**Comment by Cyberboss** [comment]
There's also much simpler tooling to read the player counts of servers directly from DD itself like how https://tgstation13.org/ does it

**Comment by Cyberboss** [comment]
The world topic `ping`, should return the number of players plus 1

**Comment by Cyberboss** [comment]
I'll leave this on the backlog though if someone else wants to take a shot

**Comment by Cyberboss** [comment]
Mmm, this can't be guaranteed on non-DMAPI servers. Because of this I'm not inclined to implement it
