### ISSUE TITLE
Discord Bots Disconnect at Irregular Intervals

### ISSUE THREAD

**Issue by MCterra10** [tgstation/tgstation-server#1250]
**Describe the bug**
Server starts a job to reconnect chat bot which runs indefinitely, with the bot unresponsive in the meantime. Reconnecting requires stopping the bot, re-entering the connection string and toggling it off and on.

**To Reproduce**
Wait until bot breaks

**Expected behavior**
Bot doesn't disconnect 

**Logs**
Submitted to cyberboss in DM

**Server State: (please complete the following information):**
 - OS: Windows Server Standard 2019
 - Version: tgstation-server v4.10.5
 - Database Type/Version: MySQL 8.0.23
 - BYOND Version Used: Multiple
 - git Repository Used: austation/austation and austation/goonstation
 - Origin Commit hash Used: Multiple
 - Active Test Merges: None
 - Client Version: Forgot

**Comment by Cyberboss** [comment]
This is related to https://github.com/discord-net/Discord.Net/issues/960

**Comment by Cyberboss** [comment]
Still an issue -_-
