### ISSUE TITLE
Occasionally upon process suspension, TGS will fail to detect that the DD process was suspended leaving it inaccessible

### ISSUE THREAD

**Issue by Crossedfall** [tgstation/tgstation-server#1279]
**Describe the bug**
For whichever reason, when TGS goes to suspend the DD process as part of the below, it throws a `Win32Exception: ERROR_ACCESS_DENIED` error and fails to detect that the process was in-fact suspended. The process will remain suspended unless a tech manually resumes it or the TGS-watchdog terminates the process after it fails to check-in. 
https://github.com/tgstation/tgstation-server/blob/ae1f0f46278d635a27951ecc9b6a1d6b86442750/src/Tgstation.Server.Host/Components/Watchdog/WindowsWatchdog.cs#L180-L209 

This happens sporadically and without any obvious pattern, so I cannot provide reliable reproduction steps.

**Logs**
[logs.log](https://github.com/tgstation/tgstation-server/files/6620822/logs.log)

**Server State: (please complete the following information):**
 - OS: `Windows Server 2019`
 - Version:  `4.11.1`
 - Database Type/Version: `MariaDB`
 - BYOND Version Used: `514.1556`
 - git Repository Used: https://github.com/beestation/beestation-hornet
 - Origin Commit hash Used: https://github.com/BeeStation/BeeStation-Hornet/commit/bf836ed45b60d585dde6742da92a9e51355425a7
 - Active Test Merges:  https://github.com/BeeStation/BeeStation-Hornet/pull/4415
 - Client Version: 2.1.2.0

![image](https://user-images.githubusercontent.com/26130695/121286697-d2feb900-c8a5-11eb-83c9-af938a3cf760.png)

**Additional context**

- TGS is installed and running as a service
- Windows has not logged any application or system errors around the time of suspension
- There haven't been any other obvious problems on the system which could correlate with this
- The system is running as a VM with QEMU acting as the virtualizer
- If a tech logs onto the machine and manually resumes the process before the watchdog kills it, it will work as though nothing happened. 
- With the exception of a single different TGS related outage, all non-maintenance downtimes for [Sage](https://status.beestation13.com/report/uptime/e30dc2aafbebce19b6ed8616f96315bb/) and [Golden](https://status.beestation13.com/report/uptime/4ae6cf516c262e7001365550a48c2009/) relate to this issue

**Comment by ike709** [comment]
I'll pay $50 for this to be fixed.
