### ISSUE TITLE
Allow for configurable `ChatManager.CommonMention`

### ISSUE THREAD

**Issue by ZeWaka** [tgstation/tgstation-server#1280]
**Is your feature request related to a problem? Please describe.**
Not exactly.

**Describe the solution you'd like**
Title, I would like to be able to change the chat prefix from `!tgs` to an arbitrary string. This could be strings such as:
* `.tgs`
* `]server`
* `;`

**Describe alternatives you've considered**
There are none that I can think of.

**Additional context**
no other context - tried implementing this and it was a pain to get yml appsettings propagating down to the discordprovider from the chatmanager level

**Comment by Cyberboss** [comment]
Duplicate of #1237
