### ISSUE TITLE
Deployments dont track TMs properly

### ISSUE THREAD

**Issue by AffectedArc07** [tgstation/tgstation-server#1281]
**Describe the bug**
![image](https://user-images.githubusercontent.com/25063394/121814409-dc52a180-cc68-11eb-80bd-b38347d47478.png)

**To Reproduce**
1. Make a deployment with testmerges
2. Let it auto update a few times
3. Observe

**Expected behavior**
Deployments do not track TMs properly

**Logs**
Provided over discord on request

**Server State:**
 - OS: Windows
 - Version: 4.12.0 (API: 9.0.01 | DMAPI: 5.3.0)
 - Database Type/Version: MariaDB
 - BYOND Version Used: 513.1536
 - git Repository Used: https://github.com/ParadiseSS13/Paradise
 - Origin Commit hash Used: Multiple
 - Active Test Merges: Multiple
 - Client Version: 2.1.2.0

**Additional context**
N/A

**Comment by AffectedArc07** [comment]
Update

This is **NOT** just an API bug with bad data, as TMs are not passed into the DMAPI either, though they are present on the server.

**Comment by Cyberboss** [comment]
For reference, this is likely because of the disgusting shitcode meant to de-duplicate test merges by reusing commits in the RepositoryController.

**Comment by Cyberboss** [comment]
Cannot reproduce, though I'll keep trying

**Comment by Cyberboss** [comment]
Found the issue

**Comment by Cyberboss** [comment]
So what was happening is the test merges were migrating to the latest deployment instead of being duplicated
