### ISSUE TITLE
Lack of submodule update on hard reset to origin

### ISSUE THREAD

**Issue by ZeWaka** [tgstation/tgstation-server#1284]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I reset hard to origin but my submodules don't update.

**Describe the solution you'd like**
I would like `git submodule update` (iirc) to be ran after hard resetting to origin.

**Describe alternatives you've considered**
> RepoResetOrigin.sh
```bash
#!/bin/bash
echo "Updating submodules..."
cd .. # Configuration
cd .. # Instance
cd Repository
cd +secret
# Get credentials ready
git remote set-url origin "https://voremedaddy:$PAT_THE_FRIENDLY_FROG@github.com/goonstation/goonstation-secret.git"
git pull origin master
```

**Additional context**
none

**Comment by Cyberboss** [comment]
Wow, I just like... totally forgot about updating submodules even though it's in V3.

**Comment by Cyberboss** [comment]
Requires API update
