### ISSUE TITLE
Setup a posix signal to handle gracefully stopping then exiting, for docker service updates

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation-server#1286]
**Is your feature request related to a problem? Please describe.**

Deploying new revisions of docker stacks will cause docker to kill the current ones then deploy the new ones. Under an ansible IaC setup, it can be hard to predict when this will happen.

**Describe the solution you'd like**
Docker update policy set to SIGTERM or SIGUSR* and 5 hours shutdown timeout, tgs gets this signal and gracefully stops all instences, once all instances are stopped, it shuts down.

**Additional context**
We talked about this on #opsbus

**Comment by Cyberboss** [comment]
Gonna be SIGUSR1
