### ISSUE TITLE
DreamDaemon option to direct stdout/err to a file

### ISSUE THREAD

**Issue by Wirewraith** [tgstation/tgstation-server#1299]
**Is your feature request related to a problem? Please describe.**
When starting a DreamDaemon instance, stdout and stderr are dumped to the main TGS logs.

**Describe the solution you'd like**
An option to direct output to a file of our choice.

**Comment by Cyberboss** [comment]
Shove it in Diagnostics

**Comment by Cyberboss** [comment]
#1442
