### ISSUE TITLE
Insert entries into CompileJobs when the job starts

### ISSUE THREAD

**Issue by Wirewraith** [tgstation/tgstation-server#1318]
**Is your feature request related to a problem? Please describe.**
I would like an easier way to globally determine how many active compile jobs there are. Typing for jobs does not exist and sounds hard, but CompileJobs is a table that does exist and modifications to when entries are added to it would accomplish this purpose.

**Describe the solution you'd like**
Instead of only inserting a CompileJobs entry when a compile job finishes, insert it when a compile job starts. 

**Describe alternatives you've considered**
It is possible to get the active compilations by checking the description field of Jobs entries. But that's gross.

**Comment by Cyberboss** [comment]
Important to remember when tackling this is that we currently determine the latest completed compile job by selecting the latest of these entries, so that will have to be changed.

**Comment by Cyberboss** [comment]
They don't need it anymore
