### ISSUE TITLE
Super-admins with global permissions for all instances

### ISSUE THREAD

**Issue by Wirewraith** [tgstation/tgstation-server#1327]
**Is your feature request related to a problem? Please describe.**
Sometimes I want a user to be able to do everything to instances (e.g. myself as owner, or a script) without having to manually add the user to each instance, and laboriously click every permission checkbox.

**Describe the solution you'd like**
Either:
- The concept of a super-admin/user/whatever that bypasses the permission system altogether, allowing it to perform any action.
- Or, a global permission set system that applies to every instance.

**Describe alternatives you've considered**
See above mention of "laboriously".

**Additional context**
I'm lazy and don't want to click two million checkboxes whenever I add a new instance.

**Comment by Cyberboss** [comment]
Gonna scrap this one as it would take a substantial refactor of the permissions system to facilitate it
