### ISSUE TITLE
No option to enable the webclient.

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation-server#133]
There doesn't seem to be a command for telling dream daemon to enable the webclient.

**Comment by Cyberboss** [comment]
@MrStonedOne Are you aware of a command line option that enables this?

**Comment by Cyberboss** [comment]
Wait, nvm it's stored in the cfg/daemon.txt

**Comment by JamieH** [comment]
@Cyberboss  `-webclient`
