### ISSUE TITLE
Symlinks are reporting duplicated space usage.

### ISSUE THREAD

**Issue by AffectedArc07** [tgstation/tgstation-server#1331]
**Describe the bug**
Symlinks make directories appear to take up double the space at the drive level
![image](https://user-images.githubusercontent.com/25063394/133476504-dc2c53a5-2022-4c02-aea7-9b566e227cab.png)

Note how looking at the folder in file explorer shows the correct size, but the drive reports otherwise
![image](https://user-images.githubusercontent.com/25063394/133476529-688a77d7-4b8e-4acc-8e39-d630b05a68e5.png)

This server only has TGS4 on it. When you use symlinks, windows duplicates the space used for the drive view which is probably going to break things.

This thread may prove useful for creating a link which doesnt do this
https://social.technet.microsoft.com/Forums/windows/en-US/79afc36f-c893-459f-9865-8e7bc8ee8d98/symbolic-links-causing-files-to-take-up-twice-the-memory?forum=w7itprogeneral

**To Reproduce**
Make a large static files folder and notice your space be duplicated on the drive view

**Expected behavior**
Correct space reporting

**Logs**
N/A

**Server State: (please complete the following information):**
 - OS: Windows 10
 - Version: 4.14.2
 - Database Type/Version: MariaDB
 - BYOND Version Used: 514.1566
 - git Repository Used: ParadiseSS13/Paradise
 - Origin Commit hash Used: N/A
 - Active Test Merges: N/A
 - Client Version: 2.3.0.0

**Additional context**
Windows symlinks seem flaky.

**Comment by Cyberboss** [comment]
Windows bug, doesn't actually affect disk space like this. The display isn't showing the true value.

**Comment by AffectedArc07** [comment]
Real issue was this
![image](https://user-images.githubusercontent.com/25063394/134255003-77ed1bb4-414f-448b-8d24-9ceba037c037.png)
