### ISSUE TITLE
Additional configuration options for Discord bot embeds

### ISSUE THREAD

**Issue by Wirewraith** [tgstation/tgstation-server#1332]
**Is your feature request related to a problem? Please describe.**
TGS is cool and all but sometimes, y'know, I just wanna personalize it a little bit for the viewing pleasure of my fellow admins. For example, the Discord bot embeds something similar to this:

![image](https://user-images.githubusercontent.com/15199527/134237925-7b44440d-fdc7-469f-8138-6e612154eb1d.png)

But you see, I would like to change that tg icon and ideally the "tgstation-server" bit too, for that full whitelabel experience.

**Describe the solution you'd like**
Either a global configuration option for discord embed icon + title in appsettings, or extra fields for the same options in the instance bot config area.

**Describe alternatives you've considered**
Literally only forking the repo just for this extremely minor thing.

**Additional context**
You can consider this, how shall we say, "low" priority.

**Comment by Cyberboss** [comment]
Just make this a flag in the Discord connection string

**Comment by Cyberboss** [comment]
Yeah best I can do is an option to turn it off
