### ISSUE TITLE
PUT endpoints should allow you to assign all of the objects without a separate POST

### ISSUE THREAD

**Issue by Crossedfall** [tgstation/tgstation-server#1354]
**Is your feature request related to a problem? Please describe.**
As it is now, we need to submit separate POST actions to configure basic parameters like the `comitterName` and `comitterEmail` for the Repository endpoint; or the `online` boolean for the Instance endpoint. This is a bit annoying from a scripting and automation perspective since it means building in several redundant requests which adds unnecessary bloat and delays (Especially when setting up the repository since TGS rejects any changes until the repo finishes cloning).

**Describe the solution you'd like**
PUTs already accept the full parameter list (based on the endpoints I commonly use `Instance`/`Repository`), it would be nice if it actually applied them instead of defaulting several of the options regardless of what I send it.

**Additional context**
`PUT http://tgs.url:5000/Repository`
```json
{
    "origin": "https://github.com/beestation/beestation-hornet",
    "recurseSubmodules": null,
    "reference": null,
    "committerName": "ss13-beebot",
    "committerEmail": "56381746+ss13-beebot@users.noreply.github.com",
    "accessUser": null,
    "accessToken": null,
    "pushTestMergeCommits": null,
    "createGitHubDeployments": null,
    "showTestMergeCommitters": null,
    "autoUpdatesKeepTestMerges": null,
    "autoUpdatesSynchronize": null,
    "postTestMergeComment": null,
    "updateSubmodules": true
}
```

will return & set

```json
{
    "origin": "https://github.com/beestation/beestation-hornet",
    "activeJob": {
        "startedBy": {
            "id": 1
        },
        "description": "Clone repository https://github.com/beestation/beestation-hornet",
        "startedAt": "2021-12-28T06:17:46.189178+00:00",
        "cancelled": false,
        "cancelRightsType": 2,
        "cancelRight": 4096,
        "id": 2
    },
    "committerName": "tgstation-server",
    "committerEmail": "tgstation-server@users.noreply.github.com",
    "pushTestMergeCommits": false,
    "createGitHubDeployments": false,
    "showTestMergeCommitters": false,
    "autoUpdatesKeepTestMerges": false,
    "autoUpdatesSynchronize": false,
    "postTestMergeComment": false,
    "updateSubmodules": true
}
```

**Comment by Crossedfall** [comment]
Couldn't figure out if this was intended behavior or not, so I just listed it as a feature addition.

**Comment by Cyberboss** [comment]
Note in the case of Instances I believe there is a "Good reason" (tm) that they are seperate.

Repo stuff is bugged though
