### ISSUE TITLE
Provide the branch of active deployment in `PreCompile` event

### ISSUE THREAD

**Issue by martinlyra** [tgstation/tgstation-server#1356]
**Is your feature request related to a problem? Please describe.**
I work on a fork of a codebase and server that has two branches, one for old stable master and another for unstable that they (used to) commit lot of development changes to. My codebase currently only has one branch, and is not labelled `master` like on tgstation, and for the sake of knowing what branch is active on the deployment would be helpful. Specially when getting the revision data for putting in issue repots.

**Describe the solution you'd like**
```DM
/datum/tgs_revision_information
	//...
	var/branch_name // something like this
```
**Describe alternatives you've considered**
Writing an EventScript that copies the `.git` folder to the active deployment after a successful compilation/deployment. As the local TGS-less version uses `.git/HEAD` to find the active branch, this is the case on old Baycode versions, like [this codebase](https://github.com/Haven-13/Haven-Urist).

**Comment by Cyberboss** [comment]
So, I thought this would be easy but it's not. Revision info is stored in the compile jobs as `Tgstation.Server.Api.Models.Internal.RevisionInformation`. This is the class that we'd have to add the info to but because of how widespread the use is we'd have to go over it with a fine toothed comb to check that we add the current repository reference to it wherever it is created.

**Comment by Cyberboss** [comment]
This is doable... Branches would have to be a many relationship to the rev info.

**Comment by Cyberboss** [comment]
@martinlyra I'm going to propose a different solution that'll take some more effort on your part, but is a lot easier on the codebase. I'll add the repository's active reference as a 4th argument to the `PreCompile` script. From there, you can generate a .dm file in `Configuration/CodeModifications` with that information and access it at runtime.
