### ISSUE TITLE
Adjust ReleaseNotes to delete expected next minor version milestone when releasing a major version

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation-server#1386]
i.e. Milestone 4.20.0 had to be manually deleted when releasing 5.0.0 from 4.19.1

**Comment by rajat-tomar** [comment]
Hey, Can you please elaborate a little more on this?

**Comment by Cyberboss** [comment]
Sorry for missing your comment @rajat-tomar. You can take a look at the fix above if you're still interested.
