### ISSUE TITLE
Wierd test merge job stopping-but-not-really?

### ISSUE THREAD

**Issue by TiviPlus** [tgstation/tgstation-server#1403]
TGMC issue

Server last updated several hours ago
Log in
Go to Repository menu
Add some new tms remove some old ones and click

Afterwards it shows like it canceled/stopped
![image](https://user-images.githubusercontent.com/57223640/193808968-d700f05f-93a9-42d5-87dd-5f56187988b9.png)
And shows the error: RepoBusy: The repository is busy with another operation!

Compile meanswhile says no issues
![image](https://user-images.githubusercontent.com/57223640/193809297-dd29e2a6-67dd-4a26-9fdf-a7d63e3ca554.png)

meanwhile everything seems to be working fine and discord bot says deployment completed
https://discord.com/channels/498569646014857217/528043835213873172/1026817557296066620

Click cancel and do exact same thing again
No error and everything is green
![image](https://user-images.githubusercontent.com/57223640/193809704-bd81f910-4dbb-4ef6-9aa3-ddaaa821eca9.png)

**Comment by Cyberboss** [comment]
Issue is the request cancellation token being used inside the scope of the repository update job.

HOW HAS THIS NEVER BEEN FOUND BEFORE NOW? IT MUST BE CLOUDFLARE
