### ISSUE TITLE
Sybil bot is not reporting new rounds

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation-server#141]
The last time it reported a new round was at noon EST, April 7th. It still gives out compile updates and such, but is not announcing new rounds.

**Comment by optimumtact** [comment]
@MrStonedOne

**Comment by optimumtact** [comment]
@tgstation/toolmasters

**Comment by MrStonedOne** [comment]
I had to re-do it's bot config, I might have forgotten one.

**Comment by MrStonedOne** [comment]
fixed
