### ISSUE TITLE
TGS Chatbot sends messages to the wrong channel

### ISSUE THREAD

**Issue by Cyprex** [tgstation/tgstation-server#1429]
**Describe the bug**
TGS doesn't send messages to the correct channel, or swallows messages & sends them to another channel.
![](https://i.imgur.com/pmnpevg.png)
![](https://i.imgur.com/ftP8j9a.png)
Actual Result, first the admin channel:
![](https://i.imgur.com/M18wLY3.png)
Now the status channel. Beyond that screenshot there's only Deployment messages.
![](https://i.imgur.com/h1s2zTw.png)
**To Reproduce**
I honestly don't know.

**Expected behavior**
TGS to send the messages to the correct channel

**Logs**
No idea if these don't contain sensitive information, I've reported it in coderbus #hosting-questions as well.

**Server State: (please complete the following information):**
 - OS: Ubuntu 22.04
 - Version:
 - Database Type/Version: MariaDB 10.06
 - BYOND Version Used: 514.1589
 - git Repository Used: https://github.com/bubberstation/Bubberstation
 - Origin Commit hash Used:
 - Active Test Merges:
 - Client Version:

**Additional context**

**Comment by Cyprex** [comment]
A few things of note: I've migrated this TGS installation from another machine. By that I mean I backed up & restored the DB with mysqldump, grabbed a new copy of TGS 5.3.0, copied the old appsettings.production.yml into it. 
I also copied over this particular instance by copying the Respository Folder & GameStaticFiles, with the exception of EventScripts(I grabbed them from the repo again, there was like a gigabyte of build artifacts and whatnot from CBT & rust-g in there)

**Comment by Cyprex** [comment]
I believe I've tried enabling the chatbot(s) again afterwards.

**Comment by Cyberboss** [comment]
Not seeing anything particularly out of place here. Seems like an SS13 config issue. Check your usages of `send2chat` and make sure your config is set up correctly to route the messages to the TGS channels you want them to go to https://github.com/Bubberstation/Bubberstation/blob/master/code/__HELPERS/chat.dm
