### ISSUE TITLE
Entering an invalid password for a system login triggers an internal server error

### ISSUE THREAD

**Issue by craftxbox** [tgstation/tgstation-server#1521]
**Describe the bug**
Through the webpanel, Users can be created without specifying a password during creation (Specifically SYSTEM accounts)
Attempting to log into this system account will fail with 
`System.ArgumentNullException: Value cannot be null. (Parameter 'hashedPassword')`
As there is no password specified for the account in the database.

**To Reproduce**
1. Go to the create user tab.
2. Create a user under system identifier (With or without domain)
3. Observe user is created successfully, Without prompting password.
4. Log out of the admin account.
5. Log into the system account with any password (I used the system password)
6. Observe BUG: Server Error

![](https://transfur.science/vdytozi)
![](https://transfur.science/coftxvar)
![](https://transfur.science/sq7icbme)
![](https://transfur.science/1c92irny)
![](https://transfur.science/yxymxwx9)

**Expected behavior**
Creating an account should always request to specify a password. Or, if the system password is required, It should be used for authentication with the system

**Logs**
[message (13).txt](https://github.com/tgstation/tgstation-server/files/11667420/message.13.txt)

**Server State: (please complete the following information):**
 - OS: Windows 10
 - Version: v5.12.4
 - Database Type/Version: MariaDB (version unknown)
 - BYOND Version Used: N/A
 - git Repository Used: N/A
 - Origin Commit hash Used: N/A
 - Active Test Merges: N/A
 - Client Version:
 ```
Webpanel Version: 2cf2e2d9e05e77138cfc91d17688f2cb95a42847
Webpanel Mode: GITHUB
API Version: 9.10
```

**Additional context**
This specific system is joined to an Azure Active Directory. I am unaware and unable to test if this occurs on a regular local accounted system.

The user record as observed in DB:
![](https://transfur.science/1qcvvvs6)

**Comment by Cyberboss** [comment]
Of note, this doesn't seem to occur when I use the correct password.

**Comment by craftxbox** [comment]
> Of note, this doesn't seem to occur when I use the correct password.

My experience might be related to being joined to AAD then

**Comment by Cyberboss** [comment]
Issue they were having was #1527
