### ISSUE TITLE
request - limited accounts

### ISSUE THREAD

**Issue by steamp0rt** [tgstation/tgstation-server#168]
basically. for example, give someone a login which can _only_ update...

**Comment by MrStonedOne** [comment]
MrStonedOne> Cyberboss, i was actually thinking about that. I could see a user for 3 user modes, config/sysop (access to change tgs3 config settings), administrative(change server settings), and operational (can update/restart)

**Comment by Jordie0608** [comment]
While we're nearby, so it's written down somewhere: <Jordie> the database config tab probably shouldn't be visible

**Comment by Cyberboss** [comment]
Took care of that with the config rework

**Comment by Cyberboss** [comment]
Here's a mini design doc for how this will go

First off, system administrators always have full access and is required to create, move, detach, and assign permissions and remote access to server instances

Then I propose 3 more tiers

Ops have full control of a server instance with the exception of all the functions in [ITGAdministration](https://tgstation.github.io/tgstation-server/interface_t_g_service_interface_1_1_components_1_1_i_t_g_administration.html)

HalfOps have control of the repository, starting/restarting, and compiling the server but cannot use any other parts of the server control panel (Excluding the config page)

And ConfigOps only have access to the static directory interface while also simultaneously limited by the ACLs

I can break these down as much as further proposed. This is only going to limit which API functions a user can call. See here: https://tgstation.github.io/tgstation-server/namespace_t_g_service_interface_1_1_components.html

**Comment by Cyberboss** [comment]
Very very much addressed in V$
