### ISSUE TITLE
HTTP API v10 breaking changes notice (TGS6)

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation-server#1689]
CC @MrStonedOne and @AffectedArc07 primarily since you guys are the only ones I can think of with custom tooling for the API. Ping anyone else you can think of

I mainly want to do four main breaking changes

- Fully remove support for the based meme in Discord connection strings
- Remove the `/Byond` controller in favor of the more generic `/Engine` controller. See #1666 
- Remove references to Byond from InstancePermissionSets and CompileJobs, replace with Engine equivalent.
- **Change the root API path** from `/` to `/api`. The redirecting behavior of `/` will be changed to redirect to `/api` if it normally would not redirect to `/app`.

Of course the webpanel and desktop panel will be updated to support this.

Speak soon or forever rest in peace.

**Comment by Cyberboss** [comment]
I'm thinking it's best to do this with TGS6 rather than any other time.

**Comment by AffectedArc07** [comment]
If you're following semver then absolutely wait till TGS6.

I'm fine with these changes, just need the relevant heads up time.

**Comment by Cyberboss** [comment]
Yeah, it was always going to happen on or after V6. And I figure it's best not to delay it.

The primary blocker for V6 is OpenDream/RobustToolbox migrating to it. It'll likely be out before end of year.

**Comment by Cyberboss** [comment]
I do need @MrStonedOne to comment because he has that script for auto-roleing users. It should just be a matter of slapping `/api` in front of the routes if the V10 API is detected.

**Comment by MrStonedOne** [comment]
> I do need @MrStonedOne to comment because he has that script for auto-roleing users. It should just be a matter of slapping `/api` in front of the routes if the V10 API is detected.

![image](https://github.com/tgstation/tgstation-server/assets/7069733/7cefdf09-0e48-4015-a02b-6d69308cd096)

**Comment by Cyberboss** [comment]
Based, no problems then. This is going through.
