### ISSUE TITLE
TGS not Authenticating when Retrieving Pulls from Private Repositories on GitHub

### ISSUE THREAD

**Issue by king5327** [tgstation/tgstation-server#1694]
**Describe the bug**
When provided an up to date authentication token, TGS appears not to submit it to GitHub when fetching pull requests for testmerging, rendering the feature unusable.

**To Reproduce**
Setup:
1: Create new blank instance in the usual way.
2: Host, on GitHub, a private clone of some BYOND repository.
3: Generate a GitHub Private Authentication Token with access to the repo.
Configuration:
1: Download the repository using the token. This succeeds only when a token is provided.
2: Attempt to access the Repository tab of the instance menu.
Issue:
1: An error appears. (see log below, certain elements redacted as repo belongs to someone else)
 - GitHub returns 404s when attempting to access a private repository, even if it exists.
2: PRs on GitHub are not properly loaded to be available for test merges.
3: On analysing the error, it appears the authorization header is not submitted.

**Expected behaviour**
PRs to be correctly loaded, without a 404, and be available.

**Logs**
Note: the following log has had the org, repo, and tgs access url redacted with \<org\>, \<repo\> and \<tgspath\>
```
Webpanel Version: 4f71c9399c42fc6bcc74f8adc65fb74c02c75ee2
Webpanel Mode: GITHUB
API Version: 9.10.2

Error Code: error.github
Error Description: HttpError: Not Found

Additional Information:
{"addon":{"jsError":{"name":"HttpError","status":404,"response":{"url":"https://api.github.com/repos/<org>/<repo>/pulls?state=open","status":404,"headers":{"content-length":"117","content-type":"application/json; charset=utf-8","x-github-media-type":"github.v3; format=json","x-github-request-id":"C746:2153:1460591:29F5528:6546DA3E","x-ratelimit-limit":"60","x-ratelimit-remaining":"54","x-ratelimit-reset":"1699145288","x-ratelimit-resource":"core","x-ratelimit-used":"6"},"data":{"message":"Not Found","documentation_url":"https://docs.github.com/rest/pulls/pulls#list-pull-requests"}},"request":{"method":"GET","url":"https://api.github.com/repos/<org>/<repo>/pulls?state=open","headers":{"accept":"application/vnd.github.v3+json","user-agent":"tgstation-server-control-panel/4f71c9399c42fc6bcc74f8adc65fb74c02c75ee2 octokit-rest.js/18.12.0 octokit-core.js/3.5.1 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0"},"request":{}}}},"config":{"githubtoken":{"id":"config.githubtoken","type":"pwd","value":""},"apipath":{"id":"config.apipath","type":"str","value":"<tgspath>"},"jobpollinactive":{"id":"config.jobpollinactive","type":"num","value":15},"jobpollactive":{"id":"config.jobpollactive","type":"num","value":5},"jobswidgetdisplay":{"id":"config.jobswidgetdisplay","type":"enum","possibleValues":{"ALWAYS":"always","AUTO":"auto","NEVER":"never"},"value":"auto"},"instanceprobetimer":{"id":"config.instanceprobetimer","type":"num","value":60},"itemsperpage":{"id":"config.itemsperpage","type":"num","value":25,"min":1,"max":100},"instanceeditsidebar":{"id":"config.instanceeditsidebar","type":"enum","possibleValues":{"AUTO":"auto","COLLAPSE":"collapse","EXPAND":"expand"},"value":"expand"},"showjson":{"id":"config.showjson","type":"bool","value":false},"manualpr":{"id":"config.manualpr","type":"bool","value":true}},"stack":"d@https://tgstation.github.io/tgstation-server-webpanel/api/9.10.2/607.e33c43c8d59d9a1331e8.bundle.js:1:47907\\ngetPRs@https://tgstation.github.io/tgstation-server-webpanel/webpanel/4.21.4/207.9f6ce71a5aab9f4a7bd0.bundle.js:1:7446\\n"}
```

**Server State: (please complete the following information):**
 - OS: Debian 9
 - Version: v5.12.7
 - Database Type/Version: N/A
 - BYOND Version Used: N/A
 - git Repository Used: Private, sorry
 - Origin Commit hash Used: N/A
 - Active Test Merges: None
 - Client Version: N/A

**Additional context**
 - Investigating this issue was done almost exclusively using GitHub's fine-grained personal access tokens. One classic token was tested, and the issue was originally discovered using a classic token.
 - In testing, I used some additional tokens, including one with all possible authorizations and one with no permissions whatsoever. The one with full access did not work any more than a necessities-only one, and the one without any access failed to download the repository.
 - With the help of Postman, I replicated the request as described in the error message, with the same 404 result. However, adding the Authorization header as prescribed by the API returned the correct result.
 - The reproduction steps are simplified, I've made the assumption that the issue here would not be affected by control, as the token worked fine when testing the API through postman.
 - In case it does somehow end up mattering: the repo is owned by an organization led by a friend of mine. I am a member of the organization with minimal permissions, and also have "write" permissions (pull, triage, push, NOT admin) on the specific repo.
 - I'd have gotten to fixing it myself but C# is arcane to me.

**Comment by Cyberboss** [comment]
Accessing the repository page through the webpanel attempts to pull data directly from GitHub. For this to work, you ALSO need to set a repository token in your local webpanel configuration. It has no way of using the token you provided to TGS.

Let me know if this didn't fix it for you.
![image](https://github.com/tgstation/tgstation-server/assets/8171642/1d7f65b7-ec38-44fb-8711-9c83b0b773ce)

**Comment by king5327** [comment]
Welp. That was it.

Each user can set their own independently, I hope.

RIP. All that time spent thinking it was on the server side of the app.

**Comment by Cyberboss** [comment]
Yes, they can
