### ISSUE TITLE
Server Sent Events not receiving Job updates

### ISSUE THREAD

**Issue by exdal** [tgstation/tgstation-server#1713]
# Case 1
Case 1 is when there are NO jobs running.
### Repro
- Log in, select instance
- Try starting any job
- Job List modal does not pop up
- Switch page, Job List modal pops up, but it only reports the very first state of job OR end-status(ex. its finished)

## The issue is valid for:
- tgstation-server-v5.17.2
- tgstation-server-webpanel-[4.27.0](https://github.com/tgstation/tgstation-server-webpanel/commit/0bd1483e70e24a829ef1f3d0d5cf80bcd123fd50)

**Comment by Cyberboss** [comment]
Nvm seen on campbell

**Comment by Cyberboss** [comment]
I've pushed https://github.com/tgstation/tgstation-server-webpanel/commit/155279e839e5ba98b1bb8648d0e3f85b0fa10e82 to the webpanel. It's a config option to force REST polling for jobs that will default to true until this is figured out.
