### ISSUE TITLE
Core dumps from watchdog failures (if enabled) are full dumps which quickly eat up diskspace

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation-server#1741]
**Describe the bug**
Since ss13 in general and /tg/Station 13 in particular use over a gb of memory, when you enable core dumps on watchdog failures it will quickly consume disk space with crash dumps until the lack of disk space starts causing the crashes.

This should be a mini dump by default with optional support for full dumps for system admins who understand the risks

**Comment by Cyberboss** [comment]
Descheduling this off V6 which needs to get out the gate
