### ISSUE TITLE
Discord bot commands slow sometimes

### ISSUE THREAD

**Issue by TiviPlus** [tgstation/tgstation-server#1745]
**Describe the bug**
Discord commands will sometimes be slow to respond
TGS broadcast works fine

**To Reproduce**
Use !tgs check in tgmc
Wait

**Expected behavior**
no wait

**Logs**
https://discord.com/channels/498569646014857217/504094319075131402/1187789098560258048 example error
https://discord.com/channels/498569646014857217/502919898700447775/1187789593513300068 #keyholder ping
https://discord.com/channels/498569646014857217/504094319075131402/1179058409295839334 oldest instance i managed to find
https://discord.com/channels/498569646014857217/504094319075131402/1186300948159664178 example of it working fine (occurred after the oldest found example)

**Server State: (please complete the following information):**
Whatever TGMC uses
 - OS: Windows Server 2012 R2
 - Version: 5.18.2
 - Database Type/Version: MariaDB
 - BYOND Version Used: 515.1610
 - git Repository Used: https://github.com/tgstation/TerraGov-Marine-Corps
 - Origin Commit hash Used: https://github.com/tgstation/TerraGov-Marine-Corps/commit/1c35e57be760fbbe93f11c5fe423ddb41ca90654
 - Active Test Merges: https://github.com/tgstation/TerraGov-Marine-Corps/pull/11624, https://github.com/tgstation/TerraGov-Marine-Corps/pull/14258, https://github.com/tgstation/TerraGov-Marine-Corps/pull/14637, https://github.com/tgstation/TerraGov-Marine-Corps/pull/14618
 - Client Version: Webpanel 5.2.0

**Additional context**

**Comment by Cyberboss** [comment]
According to @MrStonedOne the system's clock had drifted
