### ISSUE TITLE
Indicate that DMAPI validation is taking place in world.params

### ISSUE THREAD

**Issue by Absolucy** [tgstation/tgstation-server#1818]
**Is your feature request related to a problem? Please describe.**
DMAPI validation tends to have issues with things like byond-tracy, which can't detect that DMAPI validation is taking place (and it's a waste of time/memory/storage to use tracy it in the first place during validation), so having a flag set in world.params would be useful.

**Describe the solution you'd like**
A simple flag passed to DreamDaemon's world params indicating that DMAPI validation or such is taking place.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Cyberboss** [comment]
@Absolucy why not use PreCompile and PostCompile events to create a file that would only exist during DMAPI validation? Does that work?
