### ISSUE TITLE
TGS start issue on windows

### ISSUE THREAD

**Issue by Dekkar88** [tgstation/tgstation-server#1819]
![tgs1](https://github.com/tgstation/tgstation-server/assets/155282756/5f284f94-114a-47bf-981f-c42245b78036)
![tgs2](https://github.com/tgstation/tgstation-server/assets/155282756/069ab5c4-f249-4749-99dd-6a6f09498916)
**Describe the bug**
After installing on my Windows serverbox I can't seem to get it to run, the server service dosen't run, and I can't access localhost:5000 or 127.0.0.1:5000 in the browser and when I do it says ERROR: Refused connection or website not avaialble. When I check Services, the tgstation-server status is OFF, when I try to start it I get this message:  "The tgstation-server service on local computer started and then stopped. Some services stop automatically if they are not in use by the other services or pgrograms."
**To Reproduce**
1. install tgs on windows
2. afterwards, try to run the service
3. See error

Other people that have had this issue say just to switch to debian linux to fix it, but theres gotta be a way to get it to work in windows!

**Comment by Dekkar88** [comment]
Forgot to mention that someone suggested adding permissions for it to work, but when I tried to they are grayed out and not sure how to get them to unlock if this would even help at all.
![tgs3](https://github.com/tgstation/tgstation-server/assets/155282756/32267fff-5169-44b2-82ac-6c8a16b22a76)
![tgs4](https://github.com/tgstation/tgstation-server/assets/155282756/c0632aed-2796-45ae-ab9d-624c4cddb1e7)

**Comment by Cyberboss** [comment]
Please zip and send your logs from C:\ProgramData\tgstation-server

**Comment by Cyberboss** [comment]
No response from OP. Issue is almost certainly environment related.
