### ISSUE TITLE
Refactor changelog compilation to use the action framework

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation-server#187]
mmkay?

**Comment by MrStonedOne** [comment]
What is an action framework?

**Comment by Cyberboss** [comment]
#157

**Comment by Cyberboss** [comment]
Actually I'm gonna leave in the code for the changelog generation stuff and make it configurable. Duplicate of #189

**Comment by Cyberboss** [comment]
Duplicate of #189
