### ISSUE TITLE
Add player count to /api/DreamDaemon responses when server is running

### ISSUE THREAD

**Issue by Z4ph0d42** [tgstation/tgstation-server#1909]
With tgs currently there are 0 ways to see this info with out logging in. On the defauly dream deamon program this info along with the server adress is listed in plain sight.

**Describe the solution you'd like**
Add the player count and IP adress to the landing page after log in

**Describe alternatives you've considered**
none

**Additional context**
Please add this feature or I will cry and cry and cry.

**Comment by Z4ph0d42** [comment]
also an up time counter

**Comment by Cyberboss** [comment]
Open a second issue for the player counter.

Showing IP address in TGS is not happening, because it can look completely different to a remote client depending on your networking setup
