### ISSUE TITLE
A warning/error should be thrown if the database is not utf8mb4

### ISSUE THREAD

**Issue by Absolucy** [tgstation/tgstation-server#2057]
**Is your feature request related to a problem? Please describe.**

When the DB is not set utf8, it produces cryptic errors when there's unicode - usually emojis - in PR descriptions when testmerging.

**Describe the solution you'd like**
Some sort of obvious warning, or even error, if the TGS database is not UTF-8.

**Describe alternatives you've considered**
None, really

**Additional context**
>testmerging prs with emojis error
>look inside
>`latin1_swedish_ci`

**Comment by Cyberboss** [comment]
Nah, see https://github.com/tgstation/tgstation-server/blob/f3bfa228ac285c0bf40408233c4ffd678acd5211/README.md?plain=1#L354-L356
