### ISSUE TITLE
Rewrite Control Panel using WPF

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation-server#421]
@Cyberboss needs to be forcefully dragged out of 2000 and late

**Comment by Cyberboss** [comment]
A mockup: 
![untitled](https://user-images.githubusercontent.com/8171642/33327546-c2bcfae8-d425-11e7-916e-d7ed76f15b02.png)

**Comment by Cyberboss** [comment]
Open to design ideas for the content of the tabs

**Comment by MrStonedOne** [comment]
@Rockdtben  help this poor soul.

**Comment by Cyberboss** [comment]
https://github.com/tgstation/Tgstation.Server.ControlPanel
