### ISSUE TITLE
Watch dog thread crashed

### ISSUE THREAD

**Issue by hecksadecimal** [tgstation/tgstation-server#437]
Watch dog thread crashed: System.InvalidOperationException: Process has exited, so the requested information is not available.
    at System.Diagnostics.Process.EnsureState(State state)
    at System.Diagnostics.Process.get_ProcessName()
    at TGS.Server.Instance.Watchdog()

I'm not sure what might be causing this, the error is very undescriptive. 
This is a completely fresh install of tgstation-server (3.2.1.2). Followed the instructions up to compilation of the dm project, but it immediately fails to start the server.

**Comment by Cyberboss** [comment]
So what's happening is DD is starting and exiting immediately before the watchdog setup finishes. I can prevent the crash from happening, but try running DD on the Game/Live folder manually to find out what the cause of that is.

**Comment by hecksadecimal** [comment]
When I run DD manually on the live folder, it starts up as expected.

**Comment by Cyberboss** [comment]
Is your code public? Can you link the repo?

**Comment by hecksadecimal** [comment]
Sure, here's the repo.
[Skaiastation](https://github.com/hecksadecimal/skaiastation)

**Comment by Cyberboss** [comment]
Well I fixed the crash, but it doesn't explain your issue. Can I see a screenshot of your Game/Live folder?

**Comment by hecksadecimal** [comment]
![game_live_folder](https://user-images.githubusercontent.com/20251491/33676783-a8ff3f34-da84-11e7-8789-24154c343f77.PNG)

**Comment by Cyberboss** [comment]
Ok, can I get your most recent runtime.log from the data folder?

**Comment by Cyberboss** [comment]
Or, rather, the most recent one from a tgstation-server run

**Comment by hecksadecimal** [comment]
[runtime.log](https://github.com/tgstation/tgstation-server/files/1536315/runtime.log)
Seems like DD is running just fine when started from tgstation-server. I see the process in the task manager still too.

**Comment by Cyberboss** [comment]
Hmm okay, try updating to the latest version and see if it stays attached now

**Comment by hecksadecimal** [comment]
Looks like it's fixed.
