### ISSUE TITLE
Bagil isn't saving the discord config

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation-server#452]
I have added the admin discord channel config for bagil multiple times now, and it hasn't been taking...

works fine on sybil and terry

**Comment by Cyberboss** [comment]
Weird bug relating to the chat page not initializing on CP load

**Comment by Cyberboss** [comment]
Unable to repro, probably generic CP shittiness. Gonna close this a a duplicate of #421.

**Comment by Cyberboss** [comment]
Duplicate of #421
