### ISSUE TITLE
Ahelps from discord behave oddly

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation-server#479]
sure ill just copy paste this here like i care
82759 but not round related

Ahelps from discord are unable to reply against unless you initiated the ticket as player.

The name of the admin has the discord user id(ie 26565465464648) and (irc) in the name.
Ideally it should use the discord username and discriminator.

@Cyberboss

**Comment by Cyberboss** [comment]
Was fixed at some point I think
