### ISSUE TITLE
Static files editor needs to warn if the version it has open is out of date because of changes made by somebody else

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation-server#482]
I can't even begin to tell you how much annoyance this has caused because of changes being overridden, that i'm actually going to lock the config directory behind a uac prompt so people can't use the client to edit them, until this is fixed.

**Comment by Jordie0608** [comment]
Can a refresh not be run automatically when say i.e. the window switches to a new tab/file; x minutes have passed while the control panel is open and the focused/active window (+ perhaps only while user remote session is active if a local connection); a remote session is opened/closed etc.?

**Comment by Cyberboss** [comment]
#489
