### ISSUE TITLE
Testmerges don't display their exact commits being merged during compiling

### ISSUE THREAD

**Issue by deathride58** [tgstation/tgstation-server#488]
>Make major game-changing PR
>Testmerge it
>Notice a very major bug 5 minutes before the round ends
>Fix bug, force TGS to recompile after new round starts
>"Merging PR # 69"
>Disconnect and go to sleep, thinking it's recompiling from the testmerged PR's most recent commit
>Wake up in morning
>Check server
>Server is still running the very outdated commit
>Have to spend the next two hours babysitting the server to ensure the next round is running the most recent commit in the testmerged PR

Making the exact commit the testmerged PR is compiling from more clear will make sure the above doesn't happen.

**Comment by Cyberboss** [comment]
Won't fix in V3
