### ISSUE TITLE
Symlinks dont create

### ISSUE THREAD

**Issue by AffectedArc07** [tgstation/tgstation-server#521]
How to reproduce:
Clone repository
Setup BYOND
Press `Initialize Game Folders`
Go to Game/Live
Scream when the symlinks havnt been made

(This may be due to administrator account issues, I run this in an AD environment on windows server)

**Comment by Cyberboss** [comment]
Can you go to the windows event viewer and look for warnings/errors please?

**Comment by AffectedArc07** [comment]
Nothing was logged in regards to TGS3, was expecting some access denied but there wasnt, I found a workaround by using windows 7 instead of Server 2016 though. After googling how to make symlinks (To manually make them), they do require administrative rights, so I think it is either windows server doing wierd shit, or something wrong with my AD configuration. Anyway what I have works now, but this is something to look into for the future.
