### ISSUE TITLE
Server discord bots don't ping when you ask for a notification.

### ISSUE THREAD

**Issue by SpaceManiac** [tgstation/tgstation-server#569]
Repost of https://github.com/tgstation/tgstation/issues/39746 by @BeeSting12
>beesting12Today at 2:33 PM
@Mrs_Sybil notify
Mrs_SybilBOTToday at 2:33 PM
I will notify 292042839683235840 when the round ends.
------a few minutes later------
Mrs_SybilBOTToday at 2:44 PM
RELAY: Server | The Emergency Shuttle has docked with the station.
RELAY: Notice | 292042839683235840 the round has ended.
RELAY: Server | Round just ended.

**Comment by Cyberboss** [comment]
this is impossible to fix in v4 without breaking api changes. and a new major v3 version isnt something i want to divert attention to atm

**Comment by Cyberboss** [comment]
I forget how, but this definitely works now
