### ISSUE TITLE
Add v3 style memory and CPU tracking to watchdog

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation-server#611]

**Comment by Cyberboss** [comment]
Do we wanna save this as DB data?

**Comment by Cyberboss** [comment]
This should be available through the API

**Comment by remove32** [comment]
personally, capturing this and distortion as db data would be cool. fun stuff for a pretty dashboard

**Comment by Cyberboss** [comment]
@remove32 what did you mean by distortion in this case?

**Comment by remove32** [comment]
@Cyberboss wrote that comment a month ago but I think I meant time dilation / tick drift

**Comment by Cyberboss** [comment]
Delaying for now as I'm not quite sure how I want to accomplish this

**Comment by Cyberboss** [comment]
I really feel that the people that want this should just use metricbeat

**Comment by Cyberboss** [comment]
Going to implement immediate stats querying
