### ISSUE TITLE
Add Profiling API

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation-server#613]

**Comment by Cyberboss** [comment]
@ninjanomnom @MrStonedOne mind leaving what you guys told me here so I don't forget?

**Comment by Cyberboss** [comment]
@ninjanomnom Since you seem so interested in this let's get started on it. Work on designing a class to match this interface for now. Put it in `/src/Tgstation.Server.Host/Components/Watchdog`

```c#
using System;
using System.Threading;
using System.Threading.Tasks;

namespace Tgstation.Server.Host.Components.Watchdog
{
	sealed class ProfileResult
	{
		public string Proc { get; set; }
		public TimeSpan SelfCpuTime { get; set; }
		public TimeSpan TotalCpuTime { get; set; }
		public int Calls { get; set; }
	}

	interface IProfiler
	{
		Task<ProfileResult> ProfilePort(ushort port, CancellationToken cancellationToken);
	}
}
```
Seperate files for `IProfiler` and `ProfileResult` please

When you want to get started, push a copy of master branch to this repo titled `613-<name it whatever you want>` and do your work there. It'll handle the auto issue management stuff

**Comment by ninjanomnom** [comment]
I was actually starting from the opposite end with a telnet connection implementation. 

Also the best use of this functionality would be in getting a new result every x seconds. Is a single class for every proc for every profile refresh a good use of resources? Storing it directly into a database seems a better option.

**Comment by Cyberboss** [comment]
These classes will be short lived, and have to exist in order for the ORM
to process them into the database anyway.

I'm thinking the Watchdog class will handle the actual inserts since it's
already configured to access it. That way, this class can live as a
singleton used by all instances.

Don't worry about the size of the list btw. Absolute worst case is probably
no more than 1MB that will just end up being optimized by the runtime

**Comment by Cyberboss** [comment]
@ninjanomnom @SpaceManiac is this still necessary with the changes to profiling that I haven't been following?

**Comment by Cyberboss** [comment]
Probably wouldn't be regardless tbh

**Comment by SpaceManiac** [comment]
@Cyberboss it's unnecessary; the new features allow you to start and stop profiling and get JSON blobs of profile data in pure DM code

**Comment by Cyberboss** [comment]
Sweet
