### ISSUE TITLE
Discord API Disconnects bot from discord due to inactivity

### ISSUE THREAD

**Issue by TDcoolguy300** [tgstation/tgstation-server#813]
Description: The discord bot stops listening to !tgs and @ user commands, but is still capable of sending messages to the output channels. Main suspect is that Discord is disconnecting the bot from the API, as a result can no longer see messages directed at it, but is still capable of piping the output messages to the connected channels. This has only occurred once so far.

Reproduction: Let a connected bot sit inactive for a couple of days and attempt to use a command, keeping TGS on but not doing anything.

Images and Log with Trace:
![PartUno](https://i.imgur.com/16crdYh.png)
![PartDos](https://i.imgur.com/Nscd7Ss.png)

[tgs-20181026.log](https://github.com/tgstation/tgstation-server/files/2544625/tgs-20181026.log)

**Comment by Cyberboss** [comment]
Possibly fixed by #812
