### ISSUE TITLE
Scheduled repo update jobs not being cleared

### ISSUE THREAD

**Issue by francinum** [tgstation/tgstation-server#849]
![](https://file.house/azWT.png)

**Comment by Cyberboss** [comment]
Nothing here seems abnormal. What makes you think they were failing?

**Comment by francinum** [comment]
Mainly because it causes the client to terminate from running out of memory trying to store all the jobs.

`System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.`
![](https://file.house/6BeV.png)

**Comment by Cyberboss** [comment]
Are you using Windows? As a stopgap, try restarting the service.

**Comment by Cyberboss** [comment]
And I'll also need your server logs

**Comment by francinum** [comment]
I've been restarting the service.

A selection of logs: https://st.ddmers.com/~francinum/public/logs/

**Comment by Cyberboss** [comment]
Something else is happening here that's keeping the jobs in the list

**Comment by Cyberboss** [comment]
@francinum Could I tempt you to try the new releases and see if you can repro this?

**Comment by Cyberboss** [comment]
This is definitely still an issue

**Comment by Cyberboss** [comment]
Fixed in #977

**Comment by Cyberboss** [comment]
Still a thing

**Comment by Cyberboss** [comment]
Fixed in 4.2.1
