### ISSUE TITLE
IRC chatbot can't join channels with keys

### ISSUE THREAD

**Issue by LoserWasTaken** [tgstation/tgstation-server#865]
the IRC chatbot cannot join channels with keys

channels with keys are joined with `/join #channel key`

**Comment by Cyberboss** [comment]
This is probably very easy, most functional changes need to be in https://github.com/tgstation/tgstation-server/blob/dev/src/Tgstation.Server.Host/Components/Chat/Providers/IrcProvider.cs

The IrcConnectionString(Builder) will need to be updated to support a `Key` field
