### ISSUE TITLE
Tgs discord bot unsyncs from the DD instance

### ISSUE THREAD

**Issue by Carbonhell** [tgstation/tgstation-server#866]
-  Description of the issue
Ss13 custom tgs commands work at the first round after a hard reboot, but disappear the round after till another hard reboot is done:
Available commands (Type '?' or 'help' and then a command name for more details): version, byond, revision, prs, kek

-  Reproduction steps for the issue if possible
Host a server on a linux box and set up a discord bot
See how commands work the first round
Wait till round end or do a normal restart
Commands no longer exist

-  Relevent server logs, and screenshots if possible
Gonna check them once i return home

**Comment by Cyberboss** [comment]
>2 days ago

**Comment by Carbonhell** [comment]
Just to know, is this related to the OpenPort bug anyhow? Or is it a DMAPI bug?

**Comment by Cyberboss** [comment]
Completely unrelated

**Comment by Carbonhell** [comment]
Updated with more info and reproduction details

**Comment by Cyberboss** [comment]
Closing this as it's almost certainly fixed with the bridge rewrite. #935 

If it comes up again, it's something new (and likely localized to the experimental watchdog)
