### ISSUE TITLE
Having problems installing

### ISSUE THREAD

**Issue by randomcat666** [tgstation/tgstation-server#873]
Hi,
I've got a windows server up and running and I wish to install TGstation-server. I'm having difficulty with it because whenever I run TGstation.Sever.Host.Service I get the error 

"You are running the TGS windows service executable directly. It should only be run by the service control manager. Would you like to install and configure the service in this location"

How do i get around this? Because there is a service installed now but it refuses to run and there is nothing I can do. I cannot even remove said service at the moment.

Edit: the other problem I have is in my services.msc I have /tg/station server 4 as <failed to read description. Error code: 2”

And if I click on it it says “the system cannot find them file specified”

If I run it it says “windows could not start /tg/station server 4 service on local computer. Error 1058: the service can not be started either because it is disabled or because it has no enabled devices associated with it.”

**Comment by Cyberboss** [comment]
Can you try running `Tgstation.Server.Host.Service.exe -u`?

**Comment by Cyberboss** [comment]
I ran into this while setting up a demo so it does exist

**Comment by Cyberboss** [comment]
Fixed in above PR
