### ISSUE TITLE
Issue mapping discord channels with a disabled (?) provider

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation-server#896]
![image](https://user-images.githubusercontent.com/8171642/72485821-00d9ee00-37d7-11ea-8dcd-1f2bdaa3dcb1.png)

In https://github.com/tgstation/tgstation-server/tree/tgstation-server-v4.0.1.4

**Comment by Autisem** [comment]
Something similair/same thing happend to me aswel while trying to configure the bot, the server is online but it wont get into the bot

**Comment by AffectedArc07** [comment]
This has caused crashloops for me before, usually happens when discord itself goes offline and then requires a restart of the TGS4 service.

**Comment by Cyberboss** [comment]
The issue lies in how "channel mapping" is performed in discord. Ideally it shouldn't require a connection, however we want to give some metadata to the DMAPI that can't be derived from just the ID (Such as the Guild name and channel name).

https://github.com/tgstation/tgstation-server/blob/master/src/Tgstation.Server.Host/Components/Chat/Providers/DiscordProvider.cs#L200

Maybe we can work around this by just providing "<Unknown>" for those values until we can establish a connection. The problem would then lie in updating the list of channels that needs to be returned by that function at some point.

https://github.com/tgstation/tgstation-server/blob/master/src/Tgstation.Server.Host/Components/Chat/Chat.cs#L398

**Comment by Cyberboss** [comment]
As it stands, there's also a `NullReferenceException` that can get thrown by this function if  the API fails to get the channel for any reason.

**Comment by Cyberboss** [comment]
I think the key here is there needs to be a retry mechanism for disconnected providers. Currently, if a provider fails to connect (will have to check discord api documentation, but) it will stay disconnected until a user intervenes.

ChatBot should have an adjustable timespan for attempting reconnect operations.
