### ISSUE TITLE
Files arent alphabetically ordered when running on linux

### ISSUE THREAD

**Issue by AffectedArc07** [tgstation/tgstation-server#897]
Dont know if this is server side or client side, but posting it here
![image](https://user-images.githubusercontent.com/25063394/72539601-6f6e8880-3877-11ea-8d1a-9b3f620ca6f2.png)
This doesnt alphabetically order, but only when running under linux. On windows its perfectly ordered.

**Comment by Cyberboss** [comment]
Difference in enumerating files on windows vs linux. Just a sort by name is needed before adding the entry lists to `results` here: https://github.com/tgstation/tgstation-server/blob/master/src/Tgstation.Server.Host/Components/StaticFiles/Configuration.cs#L185

**Comment by Cyberboss** [comment]
Why didn't this close?
