### ISSUE TITLE
Updating to TGS 4.0.2.0 breaks itself

### ISSUE THREAD

**Issue by yoyobatty** [tgstation/tgstation-server#916]
If your issue is for the web control panel, please report it here instead: https://github.com/tgstation/tgstation-server-control-panel

Please include:

- A description of the issue:

After trying to update to TGS 4.0.2.0 it keeps erroring trying to load the docker image and is on an endless reboot cycle.

- Reproduction steps for the issue if possible:

Basically you update to the latest version of TGS via TGS control panel and starts updating, WD says it's detaching then the docker image just non-stop reboots
- Relevent server logs, and screenshots if possible

![image](https://user-images.githubusercontent.com/32651551/78823361-8f12da00-79aa-11ea-9dbf-6d2702c77152.png)

Complains about a dotnet installation.

**Comment by Cyberboss** [comment]
The dotnet framework used changed from 4.0.1.4 to 4.0.2.0. This update is going to require a full container rebuild. Here's what I would do:

Make sure your instance and configuration data is safe (unless you'd rather recreate it). If they are alreaedy on a custom volume you should be able to recreate it using the same command line as before. If not, use `docker cp /config_data/appsettings.Production.json <Local destination>` to copy your config out and `docker cp <path to instance> <Local destination>` for each instance.

After that, recreate the container with the same command line you initially used (making sure to point the volumes to the copied files if you need to). Use the `tgstation-server:latest` image.
