### ISSUE TITLE
Canceling compiling doesn't work right. (and other bugs around the compiling state)

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation-server#95]
The compiling state is the longest active state the tools will be in (by far).

Atm, canceling during compiling waits for the compile to finish, and then just doesn't stage the update. This isn't how one would expect that to work. It should just proc kill the compiler process.

Starting a new job while it's already compiling doesn't do anything right. It just fails to start the compiler, then the original compile job continues. No warning about an active task, nothing.

Ideally it should be a pop up modal. Giving 3 options, abort, cancel current job and continue, and forcefully continue.

Actually, if it's a compile its in the middle of doing, it should just abort the compile and do the new job, no prompts.

The way tgs2 did this, was actually a 10 second prompt before the compile started, giving the user the chance to stop, as well as the ability to just close it during the compile to abort, and a double warning next update run about a unfinished state, and the possibility the update job was still running. (because it had no way of knowing)

Being forced to wait 3 to 5 minutes to do something else if you realized you made a mistake or want to amend the update job isn't ideal

**Comment by Cyberboss** [comment]
That's odd, it SHOULD be terminating the process

**Comment by MrStonedOne** [comment]
https://github.com/tgstation/byond-server
