### ISSUE TITLE
Remote retrieval of DreamDaemon logs

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation-server#954]
Logging DreamDaemon's stdout/stderr on Linux would be useful, especially for debugging things such as extools.

Would also require controlpanel integration.

**Comment by Cyberboss** [comment]
Pushing that data through the API isn't possible until we get proper SSE support (#829).

We'll just write it to the logs for now, downloading those through the API will come much sooner (#884)

**Comment by steamp0rt** [comment]
Why SSE instead of WebSockets?

**Comment by Cyberboss** [comment]
What do we need the push functionality for?

**Comment by steamp0rt** [comment]
good point

**Comment by Cyberboss** [comment]
This was added to trace logs in 4.2.1

**Comment by Cyberboss** [comment]
Since SSE support is scheduled for 4.4.0, we'll include this in 4.5.0.

It can possibly be done on windows with User32 hacks

**Comment by Cyberboss** [comment]
With #1042 we can now log on Windows

**Comment by Cyberboss** [comment]
DreamDaemon is now logged to the diagnostics folder. If an admin wants it to be available remotely, they can create a symlink in the Configuration folder to the Diagnostics folder
