### ISSUE TITLE
Compile TGUI 

### ISSUE THREAD

**Issue by JamieH** [tgstation/tgstation-server#98]
It'd be nice if it handled compiling TGUI :)

**Comment by MrStonedOne** [comment]
Requiring node.js be installed on the server however would be lame

**Comment by Cyberboss** [comment]
Why though? It's updated in the repo.

**Comment by JamieH** [comment]
Who updates it? IMO it should be like the changelog script

**Comment by MrStonedOne** [comment]
https://github.com/tgstation/byond-server

**Comment by Cyberboss** [comment]
Use the preaction framework :^)

**Comment by Cyberboss** [comment]
Seriously the, the direction to go is AWAY from anything not generic
