### ISSUE TITLE
Failed compile

### ISSUE THREAD

**Issue by JamieH** [tgstation/tgstation-server#99]
![](https://share.jamiehankins.co.uk/ShareX/2017/07/mstsc_2017-07-03_00-21-35.png)

**Comment by Cyberboss** [comment]
This happens when it tries to push the changlelog, an alternative is to "Reset to Remote" + `Generate Changelog` on the Repository tab and `Copy From Repo and Compile` on the `Server` tab. That'll bypass the Commit and Push stages

**Comment by Cyberboss** [comment]
Is this consistent? Seems like a fluke in the connection to github.

**Comment by Cyberboss** [comment]
What I'll probably do is guard against Commit/Push errors and just have them complain in the server log

**Comment by JamieH** [comment]
Appears to have been a fluke

**Comment by MrStonedOne** [comment]
Ya, compiling the changelog HAS to be optional, and not errors nonblocking. same for pushing it.

In fact, you should have a failure plan for every discrete action you do on these, planning to only abort if you can't recover, and that should be rare case.

This has to be robust, not "proper"

**Comment by MrStonedOne** [comment]
https://github.com/tgstation/byond-server
